displayName: SW OAuth
type: middleware
import: github.com/ZeroGachis/traefik-block-terminated-clients

summary: 'Traefik plugin for OAuth at Smartway'

iconPath: .assets/icon.png

testData:
  JwksEndpoints:
    
